# Generated by Django 4.0.2 on 2022-05-19 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_producto', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('codigo', models.CharField(max_length=15)),
                ('marca', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
